# Makefile for readdir

lib.name = readdir

class.sources = src/readdir.c

datafiles = src/readdir-help.pd readdir-meta.pd LICENSE.txt README.txt

# This Makefile is based on the Makefile from pd-lib-builder written by
# Katja Vetter. You can get it from:
# https://github.com/pure-data/pd-lib-builder

include ../pd-lib-builder/Makefile.pdlibbuilder
